hidapi:
  ip: 192.168.50.228
  port: 5000
  endpoints:
    mouse_click: /mouse/click
    press_key: /keyboard/press

hostapi:
  ip: 192.168.50.200
  port: 5055
  endpoints:
    parse_title: /window/parse-title
    mouse_goto_xy_relative: /mouse/goto_xy_relative
    screen_ocr: /screen/ocr
    window_activate_topmost: /window/activate-topmost
    window_move: /window/move
    autorun_state: /screen/autorun-state
    ocr_health: /screen/ocr/health
    ocr_zen: /screen/ocr/zen
    ocr_exp_per_minute: /screen/ocr/exp_per_minute
    mouse_position_relative: /mouse/position-relative
    mouse_position: /mouse/position
    send_message: /send_message
    send_enter: /keys/send-enter
    find_templates: /screen/find-templates
    find_and_hover: /screen/find-and-hover
    screen_map: /screen/map
    screen_capture: /screen/capture.png


playerapi:
  ip: localhost
  port: 5065
  endpoints:
    run_scraper_on_demand: /api/scraper/force

scraper:
  interval: 2
  persist_interval: 10

mainplayer:
  nickname: AleElfisko
  character_type: Elf

secondaccount:
  nickname: AleToBot
  character_type: Dark_Knight

type_game: solo
